### ISSUE TITLE
Request: Separate "Again threshold" for new cards

### ISSUE THREAD

**Issue by saxoncameron** [Ajatt-Tools/mortician#6]
👋  Hey there, love the addon. I've found that 3 is a great number for the "Again threshold" in my regular reviews, but for brand-new cards it often takes me 4 or 5 times before it sinks in.

At the moment, the "Again threshold" in the Mortician Options applies to all cards: both new cards and existing cards. It'd be nice to have a separate threshold option for new cards.

**Comment by tatsumoto-ren** [comment]
Hello! Great idea, I'll make sure to work on it soon.

**Comment by tatsumoto-ren** [comment]
I've pushed a new version to AnkiWeb. Tell me if it works as expected.

**Comment by saxoncameron** [comment]
Just tested - the separate new card threshold works, but I got this error when failing a regular card: 
![image](https://user-images.githubusercontent.com/3240185/127758159-da322660-9e08-4c39-9bc6-a0498c0fdf12.png)

**Comment by saxoncameron** [comment]
Tried toggling off AJT Flexible Grading but the error persists; have had to disable Mortician for now to continue with today's reviews. Nasty bug!

**Comment by tatsumoto-ren** [comment]
Yes, apparently it is possible for a card to be in the review queue and still be a candidate for burying. Totally forgot about it. Hope it's fixed now.

**Comment by saxoncameron** [comment]
Just finished my reviews for today - I'll retest and confirm for you tomorrow 😄

**Comment by tatsumoto-ren** [comment]
Cool!

**Comment by saxoncameron** [comment]
Updated and unfortunately the issue has worsened! Whenever I exceed the "again threshold" for the respective card, I get an error.

For example, when failing an existing card for a 3rd time (3 being my "again threshold" for existing cards):
![image](https://user-images.githubusercontent.com/3240185/127808988-2933545e-6da9-49c5-ae7b-d72330549259.png)

and when I fail an NEW card for a 5th time (5 being my "again threshold" for new cards):
![image](https://user-images.githubusercontent.com/3240185/127809234-29e313d6-1b1c-4bf2-9408-bc41cd218be9.png)

**Comment by tatsumoto-ren** [comment]
Unfortunately, I can't reproduce the same issue. I'll try to do more testing. 

What version of Anki are you running?

**Comment by tatsumoto-ren** [comment]
Additionally, could you screenshot your Mortician settings?

**Comment by saxoncameron** [comment]
Here's my debug info, I'm aware I have a lot in the mix, but they've all played nicely (Mortician included) up until now. 

```
    Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
    Platform: Mac 10.15.7
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2021-08-02 13:12:37
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    AJT Browser Play Button ['182970692', 2021-07-31T04:32, 'None', '']
    AJT Flexible Grading ['1715096333', 2021-07-31T05:02, 'None', mod]
    Adjust Sound Volume ['2123044452', 2021-05-05T21:24, 'None', mod]
    AnkiWebView Inspector ['31746032', 2019-05-03T08:43, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2021-07-29T22:55, 'None', '']
    Batch Editing ['291119185', 2019-06-03T04:47, 'None', '']
    Change note type respect field and card names ['513858554', 2020-03-09T19:47, 'None', '']
    Copy2Clipboard ['1525025114', 2018-11-30T06:51, 'None', mod]
    Japanese Card Randomizer ['1476821676', 2021-07-27T08:02, 'None', mod]
    Learn now Button ['1021636467', 2020-12-26T14:36, 'None', '']
    Migaku Dictionary ['1655992655', 2021-07-03T06:55, 'None', mod]
    Migaku Editor ['1051095155', 2021-06-29T12:06, 'None', mod]
    Migaku Japanese ['278530045', 2021-04-13T08:36, 'None', mod]
    Migaku Kanji ['Migaku Kanji', 0, 'None', mod]
    Migaku Retirement ['1666520655', 2021-01-14T11:37, 'None', mod]
    Migaku Vacation ['605638174', 2021-01-14T11:36, 'None', mod]
    Mortician ['1255924302', 2021-08-01T17:07, 'None', mod]
    Remaining time for Anki 21 ['1508357010', 2020-12-14T01:14, '20.12.13i151', '']
    Review Heatmap ['review_heatmap', 2020-04-30T23:23, 'None', '']
    Speed Focus Mode auto-alert auto-reveal auto-fail ['1046608507', 2019-06-02T19:11, 'None', '']
    True Retention ['613684242', 2017-11-20T07:43, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1021636467 1046608507 1051095155 1255924302 1436550454 1476821676 1508357010 1525025114 1655992655 1666520655 1715096333 182970692 2123044452 278530045 291119185 31746032 513858554 605638174 613684242
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
```

Mortician options:
![image](https://user-images.githubusercontent.com/3240185/127810067-c8e23062-1fd4-4b41-9c2e-eac9a380e376.png)

If you still can't replicate the issue I'll try isolating the problem by toggling my addons off.

**Comment by tatsumoto-ren** [comment]
I got it. Your version of anki doesn't have `has_tag`. Ideally, I would recommend running Anki 2.1.44 or 2.1.45, your versoin was released more than 6 months ago.

I have changed it back though.

**Comment by saxoncameron** [comment]
I'm still on `*.35` as instructed for Migaku addon compatibility, which is the addon suite I use and value the most. I think their dev cycle is due to officially support `*.4X` soon, idk.

Updated, and the error message has changed 🙃 
![image](https://user-images.githubusercontent.com/3240185/127812373-3b38eb12-b776-46b7-b2a9-ba75990dbcd4.png)

Sorry this simple feature request has turned into such a pain in the ass 😅

**Comment by tatsumoto-ren** [comment]
We at Ajatt-Tools don't recommend using Migaku add-ons. There are alternatives that can replace them.

> Updated, and the error message has changed 

This time it says your version of anki doesn't have `bury_cards`. I already updated the code to work with 2.1.45, didn't expect the old calls to break.

**Comment by saxoncameron** [comment]
Thank you for your responsiveness. The latest update has fixed all of the above problems and the addon + new feature are all working as intended on my version.

RE: Migaku addons while I appreciate there are alternatives to most of them, I've found the browser extension plus the MPV plugin to integrate very neatly with their dictionary and card exporter addons which makes sentence mining immersion very slick.

Thank you again for your work! :)

**Comment by tatsumoto-ren** [comment]
I'm pretty sure the alternatives we have are better but whatever floats your boat I guess. I personally can't stand running an outdated version of anki.
